<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.2;netcoreapp3.1</TargetFrameworks>
    <LangVersion>8</LangVersion>
    <SignAssembly>true</SignAssembly>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <Nullable>warnings</Nullable>
    <AssemblyOriginatorKeyFile>Fluente.Arquitetura.EntityFramework.SqLite.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.2' ">
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.6" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.1' ">
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="D:\Projetos\dn32\Fluente.Arquitetura\Fluente.Arquitetura.Base\Fluente.Arquitetura.Base.csproj" />
    <ProjectReference Include="..\Fluent.Architecture.EntityFramework\Fluente.Arquitetura.EntityFramework.csproj" />
    <ProjectReference Include="..\Fluent.Architecture\Fluente.Arquitetura.Nucleo.csproj" />
  </ItemGroup>
  

</Project>
