<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.2;netcoreapp3.0</TargetFrameworks>
    <LangVersion>8</LangVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Fluent.Architecture.EntityFramework.SqlServer.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.2' ">
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.6" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fluent.Architecture.EntityFramework\Fluent.Architecture.EntityFramework.csproj" />
    <ProjectReference Include="..\Fluent.Architecture\Fluent.Architecture.Core.csproj" />
  </ItemGroup>

</Project>
