<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <LangVersion>8</LangVersion>
    <AssemblyOriginatorKeyFile>Fluent.Architecture.Base.snk</AssemblyOriginatorKeyFile>
    <RootNamespace>Fluent.Architecture.Core</RootNamespace>
    <Nullable>warnings</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
  
</Project>
