<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.0</TargetFrameworks>
    <LangVersion>8</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="postman\postman-user-v1.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="postman\postman-user-v1.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <PropertyGroup>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
  </PropertyGroup>
  
  <PropertyGroup>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Fluent.Architecture.EntityFramework.MemoryDatabase\Fluent.Architecture.EntityFramework.MemoryDatabase.csproj" />
    <ProjectReference Include="..\Fluent.Architecture.EntityFramework.MySQL\Fluent.Architecture.EntityFramework.MySQL.csproj" />
    <ProjectReference Include="..\Fluent.Architecture.EntityFramework.Oracle\Fluent.Architecture.EntityFramework.Oracle.csproj" />
    <ProjectReference Include="..\Fluent.Architecture.EntityFramework.PostgreSQL\Fluent.Architecture.EntityFramework.PostgreSQL.csproj" />
    <ProjectReference Include="..\Fluent.Architecture.EntityFramework.SqLite\Fluent.Architecture.EntityFramework.SqLite.csproj" />
    <ProjectReference Include="..\Fluent.Architecture.EntityFramework.SqlServer\Fluent.Architecture.EntityFramework.SqlServer.csproj" />
    <ProjectReference Include="..\Fluent.Architecture.EntityFramework\Fluent.Architecture.EntityFramework.csproj" />
    <ProjectReference Include="..\Fluent.Architecture\Fluent.Architecture.Core.csproj" />
  </ItemGroup>

</Project>
