<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.2;netcoreapp3.0</TargetFrameworks>
    <LangVersion>8</LangVersion>
    <Version>2.0.0.2-beta02</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageProjectUrl>https://dn32.github.io/Fluent.Architecture/</PackageProjectUrl>
    <RepositoryUrl>https://dn32.github.io/Fluent.Architecture/</RepositoryUrl>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Fluent.Architecture.EntityFramework.Oracle.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.2' ">
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="2.19.30" />

  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
    <!--<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.0.0" />-->
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Fluent.Architecture.EntityFramework\Fluent.Architecture.EntityFramework.csproj" />
    <ProjectReference Include="..\Fluent.Architecture\Fluent.Architecture.Core.csproj" />
  </ItemGroup>

</Project>
