version: 1.0.0-beta{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\Fluent.Architecture.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
skip_commits:
  files:
    - '**/*.md'
before_build:
- pwsh: dotnet restore
build:
  verbosity: detailed
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  server: https://www.nuget.org/packages/Fluent.Architecture
  api_key:
    secure: R4AWojxvRfOCU3ZvEj9ceEoYggmH0uaE/uLiQb15uPstmJ8SwrthvHCT2IDWmSPD