<Project>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <!--<Version>2.0.1-beta0930-01</Version>-->
    <PackageProjectUrl>https://dn32.github.io/Fluent.Architecture/</PackageProjectUrl>
    <RepositoryUrl>https://dn32.github.io/Fluent.Architecture/</RepositoryUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <Target Name="CopyPackage" AfterTargets="Pack">
    <Copy SourceFiles="$(OutputPath)$(PackageId).$(PackageVersion).nupkg" DestinationFolder="C:\Users\Marcelo\Google Drive\FOut" />
    <!--<Copy SourceFiles="$(OutputPath)$(PackageId).$(PackageVersion).nupkg" DestinationFolder="C:\Users\marcelo.souza\Google Drive\FOut" />-->
  </Target>
  
  <!--<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <Version>2.0.1-beta$([System.DateTime]::UtcNow.ToString(MMdd-HHmm))</Version>
  </PropertyGroup>-->
  
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <Version>2.0.1-beta$([System.DateTime]::UtcNow.ToString(MMdd))16</Version>
  </PropertyGroup>
  
</Project>