<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UserSecretsId>50554bb0-08e4-4a4a-a1c3-1c14a124ebfc</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.5" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fluent.Architecture.Core.Doc\Fluent.Architecture.Core.Doc.csproj" />
  </ItemGroup>
  <!--<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>UseRazorCompilation</DefineConstants>
  </PropertyGroup>-->
</Project>
