<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.2;netcoreapp3.0</TargetFrameworks>
    <LangVersion>8</LangVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Fluent.Architecture.EntityFramework.snk</AssemblyOriginatorKeyFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>2.0.0-RC-100</Version>
    <PackageProjectUrl>https://dn32.github.io/Fluent.Architecture/</PackageProjectUrl>
    <RepositoryUrl>https://dn32.github.io/Fluent.Architecture/</RepositoryUrl>
  </PropertyGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.2' ">
    <!--<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.6" />-->
    <!--<PackageReference Include="Newtonsoft.Json" Version="12.0.2" />-->
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
    <!--<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0-preview9.19423.6" />-->
    <PackageReference Include=" Microsoft.EntityFrameworkCore.Relational" Version="3.0.0-rc1.19456.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fluent.Architecture\Fluent.Architecture.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Remotion.Linq" Version="2.2.0" />
  </ItemGroup>

</Project>
