<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Fluent.Architecture.EntityFramework.snk</AssemblyOriginatorKeyFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.0.0-beta-09</Version>
    <PackageProjectUrl>https://dn32.github.io/Fluent.Architecture/</PackageProjectUrl>
    <RepositoryUrl>https://dn32.github.io/Fluent.Architecture/</RepositoryUrl>
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="2.2.6" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Fluent.Architecture.EntityFramework.snk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fluent.Architecture\Fluent.Architecture.Core.csproj" />
  </ItemGroup>

</Project>
