<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UserSecretsId>a7ab9fcc-a0db-4e02-9f6f-8daf480a005e</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <PublishTrimmed>true</PublishTrimmed>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <!--<ItemGroup>
    <None Remove="wwwroot\**\*.*" />
  </ItemGroup>-->

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <!--<EmbeddedResource Include="Views\**\*.cshtml" />-->
    <!--<_RazorComponentInclude>Views\**\*.cshtml</_RazorComponentInclude>-->
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.0.0-rc1.19457.4" />
  </ItemGroup>

  <PropertyGroup>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fluent.Architecture\Fluent.Architecture.Core.csproj" />
  </ItemGroup>

</Project>
