<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.2;netcoreapp3.0</TargetFrameworks>
    <LangVersion>8</LangVersion>
    <UserSecretsId>a7ab9fcc-a0db-4e02-9f6f-8daf480a005e</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <PublishTrimmed>true</PublishTrimmed>
    <LangVersion>8</LangVersion>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Fluent.Architecture.Core.Doc.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="FluentDoc\**\*.*" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.2' ">
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.7" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Attributes\**" />
    <Compile Remove="Services\**" />
    <Content Remove="Attributes\**" />
    <Content Remove="Services\**" />
    <EmbeddedResource Remove="Attributes\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Attributes\**" />
    <None Remove="Services\**" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Fluent.Architecture\Fluent.Architecture.Core.csproj" />
  </ItemGroup>

</Project>
